site_name: Mustafa AlShaqaq
site_url: http://mywebsite.example
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      # line_spans: : _span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

theme:
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  name: material
  font:
    text: Merriweather Sans
    code: Roboto Mono
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: material/school
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
      # education: fontawesome/solid/quote-left
  # logo: fontawesome/solid/m
  # logo: none
  # favicon: fontawesome/solid/m.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: red

      # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: red

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/malshaqaq/
    - icon: fontawesome/brands/github
      link: https://github.com/malshaqaq
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.com/citations?user=j0fzfS4AAAAJ&hl=en
copyright: Copyright © 2026 Mustafa AlShaqaq
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

